version: '3.4'

services:
  client-test:
    build:
      dockerfile: Dockerfile-client      
      context: ./LayoutAsyncLoading.Client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    ports:
      - "5000:80"
      - "5001:443"     
    volumes:
      - ./LayoutAsyncLoading.Client:/app/publish
      - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/https:ro