version: '3.4'

services:
  api-events:
    build:
      dockerfile: Dockerfile.dev      
      context: ./LayoutAsyncLoading.Api.Events
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://localhost:5005;http://localhost:5004
      - ASPNETCORE_HTTPS_PORT=5005
    ports:
      - "5004:5004"
      - "5005:5005"      
    volumes:
      - ./LayoutAsyncLoading.Api.Events:/app/publish
      - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https/